[options]
db_host = dpg-d4sbca9r0fns73a2c150-a
db_port = 5432
db_user = odoo
db_password = UpkWKxw9jwThzDrzhACwATaBGrfRv3FR
db_name = odoo_ict9

admin_passwd = Multiplica*88

addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
xmlrpc_port = 8069
log_level = info
