[options]
; Configuración de base de datos
db_host = ${DB_HOST}
db_port = 5432
db_user = ${DB_USER}
db_password = ${DB_PASSWORD}
db_name = ${DB_NAME}

; Ruta de módulos (incluye addons personalizados)
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons

; Puerto de servicio
xmlrpc_port = 8069

; Seguridad
admin_passwd = ${ADMIN_PASSWD}

; Logs (Render captura stdout/stderr, puedes quitar esta línea si prefieres)
logfile = /var/log/odoo/odoo.log
log_level = info
